# Generated by Django 3.0.3 on 2020-04-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='news_app/image/', verbose_name='Фотография'),
        ),
    ]
