# Generated by Django 3.0.5 on 2020-04-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_auto_20200420_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='news_app/image/', verbose_name='Фотография'),
        ),
    ]
