# Generated by Django 3.0.3 on 2020-04-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_title', models.CharField(max_length=50, verbose_name='Название специальности')),
                ('specialty_descriptions', models.TextField(verbose_name='Описание специальности')),
                ('specialty_logo', models.ImageField(blank=True, default=None, null=True, upload_to='main_app/image/logo', verbose_name='Логотип специальности')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя человека')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия человека')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество человека')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='Email')),
                ('age', models.IntegerField(verbose_name='Возраст студента')),
                ('course', models.IntegerField(verbose_name='Курс студента')),
                ('group', models.CharField(max_length=10, verbose_name='Группа студента')),
                ('specialty', models.CharField(max_length=50, verbose_name='Специальность студента')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='main_app/image/students', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя человека')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия человека')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество человека')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='Email')),
                ('category', models.CharField(max_length=20, verbose_name='Категоря преподавателя')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='main_app/image/teachers', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
