# Generated by Django 3.0.5 on 2020-04-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200419_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.IntegerField(default=0, verbose_name='Код учащегося'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.IntegerField(verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(max_length=10, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='patronymic',
            field=models.CharField(max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialty',
            field=models.CharField(max_length=50, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(max_length=20, verbose_name='Отчество'),
        ),
    ]
