# Generated by Django 3.0.5 on 2020-04-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200420_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=10, verbose_name='Группа')),
                ('type_practice', models.TextField(verbose_name='Вид практики')),
                ('start_practice', models.DateField(verbose_name='Начало практики')),
                ('completion_practice', models.DateTimeField(verbose_name='Завершение практики')),
            ],
            options={
                'verbose_name': 'Расписание практики',
                'verbose_name_plural': 'Расписание практики',
            },
        ),
        migrations.AlterField(
            model_name='specialty',
            name='specialty_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='main_app/image/logo/% Y/% m/% d/', verbose_name='Логотип специальности'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='main_app/image/students/% Y/% m/% d/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='main_app/image/teachers/% Y/% m/% d/', verbose_name='Фотография'),
        ),
    ]
