# Generated by Django 3.0.5 on 2020-04-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200420_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='completion_practice',
            field=models.DateField(verbose_name='Завершение практики'),
        ),
    ]
