# Generated by Django 3.0.5 on 2020-04-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200420_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='specialty',
            field=models.CharField(default=0, max_length=30, verbose_name='Специальность'),
            preserve_default=False,
        ),
    ]
