# Generated by Django 3.0.5 on 2020-04-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_practice_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='specialty',
            field=models.CharField(max_length=130, verbose_name='Специальность'),
        ),
    ]
