# Generated by Django 3.0.5 on 2020-04-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200420_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='specialty_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='main_app/image/logo/', verbose_name='Логотип специальности'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='main_app/image/students/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='main_app/image/teachers/', verbose_name='Фотография'),
        ),
    ]
