# Generated by Django 3.0.5 on 2020-04-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200421_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_part_groups', models.CharField(max_length=150, verbose_name='Название части групп')),
                ('file', models.FileField(upload_to='main_app/file/timetable/')),
            ],
            options={
                'verbose_name': 'Расписание пар',
                'verbose_name_plural': 'Расписание пар',
            },
        ),
    ]
