# Generated by Django 3.0.5 on 2020-04-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='course',
            field=models.IntegerField(default=0, verbose_name='Курс'),
            preserve_default=False,
        ),
    ]
