# Generated by Django 3.0.5 on 2020-04-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_timetable_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='branch',
            field=models.CharField(default=0, max_length=130, verbose_name='Отделение'),
            preserve_default=False,
        ),
    ]
